### ISSUE TITLE
Unable to use type System.Collections.Generic.List in F#

### ISSUE THREAD

**Issue by roboz0r** [tylerjensen/ServiceWire#49]
I have attempted to follow the Named Pipes sample code with translation into F#.

in the sample code the interface is:

```
 public interface IMyTester
 {
    Guid GetId(string source, double weight, int quantity);
    TestResponse Get(Guid id, string label, double weight, out int quantity);
    List<string> GetItems(Guid id, int[] vals);
 }
```
Which translates to 

```
type IMyTester = 
    abstract member GetId: source:string * weight:double * quantity:int -> Guid
    abstract member Get: id:Guid * label:string * weight:double * quantity: int outref -> TestResponse
    abstract member GetItems: id:Guid * vals:int array -> ResizeArray<string>
```

When used like this with a .Net 6 host and a .Net Framework 4.8 client I get the following exception:

`System.ArgumentNullException: 'Value cannot be null.Parameter name: conversionType'`

```
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at ServiceWire.DefaultSerializer.Deserialize(Byte[] bytes, String typeConfigName)
   at ServiceWire.ParameterTransferHelper.ReceiveParameters(BinaryReader reader)
   at ServiceWire.StreamingChannel.InvokeMethod(String metaData, Object[] parameters)
   at IMyTesterProxy.GetItems(Guid , Int32[] )
   at FramewrkProgram.main@9.Invoke(NpClient`1 client) in C:\Projects\ServiceWireTesting\ServiceWireTesting\ConsoleAppFramework\FramewrkProgram.fs:line 15
   at Microsoft.FSharp.Core.Operators.Using[T,TResult](T resource, FSharpFunc`2 action) in D:\a\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 4806
   at FramewrkProgram.main(String[] argv) in C:\Projects\ServiceWireTesting\ServiceWireTesting\ConsoleAppFramework\FramewrkProgram.fs:line 9
```

I found the culprit is `ResizeArray<string>`. 
`Array<string>` works. `System.Collections.Generic.List<string>` also fails with the same exception. 
 
I am using ServiceWire 5.3.4 from NuGet on both libraries.

**Comment by roboz0r** [comment]
Complete source code
```
//Library.fs
namespace SharedTypes

open System

[<Serializable>]
[<CLIMutable>]
type TestResponse = 
    {
        Id: Guid
        Label:string
        Quantity:int64
    }

type IMyTester = 
    abstract member GetId: source:string * weight:double * quantity:int -> Guid
    abstract member Get: id:Guid * label:string * weight:double * quantity: int outref -> TestResponse
    abstract member GetItems: id:Guid * vals:int array -> ResizeArray<string>
```

```
//ClientFramework.fs
open System
open SharedTypes
open ServiceWire.NamedPipes

[<EntryPoint>]
let main argv =
    let pipeName = "ServiceWireTestHost"

    using (new NpClient<IMyTester>(new NpEndPoint(pipeName))) (fun client -> 
        for i in 0..10 do
            let id = client.Proxy.GetId("test1", 3.314, 42)
            let mutable q2 = 4
            let response = client.Proxy.Get(id, "mirror", 4.123, &q2)
            let arr = [| 3; 6; 9  |]
            let list = client.Proxy.GetItems(id, arr)
            ()
    
    )

    printfn "Finished."
    Console.ReadLine() |> ignore

    0
```

```
// Net6Program.fs
open SharedTypes
open System

type MyTester() = 
    let mutable longLabel = ""
    let totalKilobytes = 140
    let rand = new Random()

    do
        let sb = new Text.StringBuilder()
        for i in 0..totalKilobytes-1 do
            for k in 0..1023 do
                sb.Append(char (rand.Next(32,126))) |> ignore

        longLabel <- sb.ToString()

    interface IMyTester with
          member this.Get(id: System.Guid, label: string, weight: double, quantity: outref<int>): TestResponse = 
              let x = {Id = id; Label = label; Quantity = 44}
              printfn "%A" x
              x

          member this.GetId(source: string, weight: double, quantity: int): System.Guid = 
              printfn "GetID(source: %s, weight: %f, quantity: %i" source weight quantity 
              Guid.NewGuid()

          member this.GetItems(id: System.Guid, vals: int array): ResizeArray<string> = 
              printfn "GetItems(id: %O, vals: %A" id vals
              seq {
                "42"
                id.ToString()
                "MyTest"
                longLabel
              }
              |> ResizeArray

let tester = new MyTester() 
let pipeName = "ServiceWireTestHost"

let npHost = new ServiceWire.NamedPipes.NpHost(pipeName)

npHost.AddService<IMyTester>(tester)
npHost.Open()

printfn "Press enter to stop"
Console.ReadLine() |> ignore

npHost.Close()

printfn "Press enter to quit"
Console.ReadLine() |> ignore

```

**Comment by tylerje** [comment]
The problem is using the default serializer between .NET 6 and the old .NET Framework because they're not compatible. If you must communicate between the two, you must inject a serializer. I think that will work, but cannot guarantee it.

**Comment by tylerje** [comment]
Try it in v5.5.0 now with a different default serializer.

**Comment by tylerje** [comment]
I'm going to close this issue for lack of response.
