### ISSUE TITLE
Fails to re-throw exceptions for async methods

### ISSUE THREAD

**Issue by prakashguru** [tylerjensen/ServiceWire#70]
Hi, 

I try to invoke an async method through named pipe channel it is working fine unless my app logic throws an exception! When my app logic throws an exception, I am getting something like the following,

```
Object of type 'Tests.PipeException' cannot be converted to type 'System.Double'.
   at System.RuntimeType.CheckValue(Object& value, ParameterCopyBackAction& copyBack, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Span`1 copyOfParameters, IntPtr* byrefParameters, Span`1 shouldCopyBack, ReadOnlySpan`1 parameters, RuntimeType[] sigTypes, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ServiceWire.StreamingChannel.InvokeMethod(String metaData, Object[] parameters)
   at ISumProxy.Divide(Double, Int32)
   at Tests.NamedPipeTests.<>c__DisplayClass1_0.<<Divide_ShouldThrow_Exception>b__0>d.MoveNext()
```

The issue seems to be in this line https://github.com/tylerjensen/ServiceWire/blob/master/src/ServiceWire/StreamingChannel.cs#L268 where it sets the outparam to Task.CompeltedTask and the next if conditions try to throw the exception from outparam. Perhaps we should assign the task value only if it is not faulted?

Am I doing something incorrect? Is there a better way to do this? 

Below is a reproducible test scenario 

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using ServiceWire;
using ServiceWire.NamedPipes;

namespace Tests;

public class NamedPipeTests
{
    private NpHost _namedPipeHost;

    [Fact]
    public async Task Divide_ShouldThrow_Exception()
    {
        Task.Factory.StartNew(StartPipeListener, TaskCreationOptions.LongRunning);

        await Task.Delay(2000);

        var npClient = new NpClient<ISum>(new NpEndPoint("8642D0EA-13B4-408F-8DBB-BB8CDEAAA0EC"), new CustomPipeSerializer());

        var exception = await Assert.ThrowsAsync<PipeException>(async () =>
        {
            await npClient.Proxy.Divide(4.0, 0).ConfigureAwait(false);
        }).ConfigureAwait(false);

        Assert.IsType<PipeException>(exception);
    }

    async Task StartPipeListener()
    {
        _namedPipeHost = new NpHost("8642D0EA-13B4-408F-8DBB-BB8CDEAAA0EC", null, null, new CustomPipeSerializer());
        _namedPipeHost.UseCompression = true;
        _namedPipeHost.AddService<ISum>(new Sum());
        _namedPipeHost.Open();
    }

}

public interface ISum
{
    Task<double> Divide(double a, int b);
}

public class Sum : ISum
{
    public Task<double> Divide(double a, int b)
    {
        if (b == 0)
            throw new PipeException("Trying to divide by zero.");

        return Task.FromResult(a / b);
    }
}

internal class PipeException : ApplicationException
{
    public PipeException(string? message = null)
        :base(message)
    {
    }
}

internal class CustomPipeSerializer : ISerializer
{
    private readonly JsonSerializerOptions _customOptions;

    public CustomPipeSerializer()
    {
        _customOptions = new JsonSerializerOptions()
        {
            Converters = { new PipeExceptionJsonConverter(), new JsonStringEnumConverter() },
        };
    }

    public byte[]? Serialize<T>(T obj) => obj == null ? null : JsonSerializer.SerializeToUtf8Bytes<T>(obj);

    public byte[]? Serialize(object? obj, string typeConfigName) =>
        obj == null ? null : JsonSerializer.SerializeToUtf8Bytes(obj, typeConfigName.ToType(), _customOptions);

    public T? Deserialize<T>(byte[]? bytes) => bytes == null || bytes.Length == 0
        ? default(T)
        : JsonSerializer.Deserialize<T>((ReadOnlySpan<byte>)bytes, _customOptions);

    public object? Deserialize(byte[]? bytes, string? typeConfigName)
    {
        Type t = typeConfigName != null ? typeConfigName.ToType() : throw new ArgumentNullException(nameof(typeConfigName));
        return  bytes == null || bytes.Length == 0
            ? t.GetDefault()
            : JsonSerializer.Deserialize((ReadOnlySpan<byte>)bytes, t, _customOptions);
    }
}

internal class PipeExceptionJsonConverter : JsonConverter<PipeException>
{
    public override PipeException? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException();
        }

        string message = "Message Not Available.";

        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndObject)
            {
                break;
            }

            if (reader.TokenType == JsonTokenType.PropertyName)
            {
                var propertyName = reader.GetString();
                reader.Read();

                switch (propertyName)
                {
                    case "Message":
                        var messageRead = reader.GetString();
                        if( messageRead != null) message = messageRead;
                        break;
                }
            }
        }

        return new PipeException(message);
    }

    public override void Write(Utf8JsonWriter writer, PipeException value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        writer.WriteString( "Message", value.Message);
        writer.WriteEndObject();
    }
}
```

**Comment by tylerje** [comment]
Thanks for the great contribution.
